/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "aofeilin的学习记录",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "$withBase('/img/logo.png')"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "作者aofeilin"
      }
    ],
    [
      "link",
      {
        "name": "keywords",
        "content": "aofeilin00000"
      }
    ]
  ],
  "pages": [
    {
      "title": "VuePress的使用",
      "frontmatter": {
        "title": "VuePress的使用"
      },
      "regularPath": "/",
      "relativePath": "ReadMe.md",
      "key": "v-7fb82cc6",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "(1).创建项目，打包及运行。",
          "slug": "_1-创建项目-打包及运行。"
        },
        {
          "level": 3,
          "title": "1.进入文档，然后执行 (npm init) 产生package.json",
          "slug": "_1-进入文档-然后执行-npm-init-产生package-json"
        },
        {
          "level": 3,
          "title": "2.配置package.json，添加下述兩行.",
          "slug": "_2-配置package-json-添加下述兩行"
        },
        {
          "level": 3,
          "title": "3.进入docs文件夹 创建 README.md文件",
          "slug": "_3-进入docs文件夹-创建-readme-md文件"
        },
        {
          "level": 3,
          "title": "4.（npm run docs:dev）",
          "slug": "_4-npm-run-docs-dev"
        },
        {
          "level": 3,
          "title": "5. (sudo npm run docs:build）也就是打包，文件会多出node_modules docs文件下会多出一个.vuepress文件。",
          "slug": "_5-sudo-npm-run-docs-build-也就是打包-文件会多出node-modules-docs文件下会多出一个-vuepress文件。"
        },
        {
          "level": 3,
          "title": "参考官网 http://caibaojian.com/vuepress/guide/getting-started.html",
          "slug": "参考官网-http-caibaojian-com-vuepress-guide-getting-started-html"
        },
        {
          "level": 2,
          "title": "(2).导航栏logo。",
          "slug": "_2-导航栏logo。"
        },
        {
          "level": 3,
          "title": "1.导航栏logo, docs/.vuepress/config.js: 配置文件的入口文件配置logo，也可以是 YML 或 toml。设置logo图片。logo图片的路径：docs/.vuepress/public: 静态资源目录 public/assets/img",
          "slug": "_1-导航栏logo-docs-vuepress-config-js-配置文件的入口文件配置logo-也可以是-yml-或-toml。设置logo图片。logo图片的路径-docs-vuepress-public-静态资源目录-public-assets-img"
        },
        {
          "level": 3,
          "title": "2.右侧导航栏。",
          "slug": "_2-右侧导航栏。"
        },
        {
          "level": 3,
          "title": "3.如果对于页面不要导航条 在md页面写:navbar:false",
          "slug": "_3-如果对于页面不要导航条-在md页面写-navbar-false"
        },
        {
          "level": 3,
          "title": "4.左边侧边栏 侧边栏分组 config.js 在md页面使用 在页面中使用##",
          "slug": "_4-左边侧边栏-侧边栏分组-config-js-在md页面使用-在页面中使用"
        },
        {
          "level": 3,
          "title": "5.左边侧边栏  多个侧边栏 config.js 在md页面使用 在页面中使用##",
          "slug": "_5-左边侧边栏-多个侧边栏-config-js-在md页面使用-在页面中使用"
        },
        {
          "level": 2,
          "title": "(3).默认主题。",
          "slug": "_3-默认主题。"
        },
        {
          "level": 2,
          "title": "(4).seo 图片和设置。",
          "slug": "_4-seo-图片和设置。"
        },
        {
          "level": 2,
          "title": "(5).添加更新时间。",
          "slug": "_5-添加更新时间。"
        },
        {
          "level": 2,
          "title": "(6).官方时间插件。",
          "slug": "_6-官方时间插件。"
        }
      ],
      "lastUpdated": "2022-05-20 10:25:43",
      "lastUpdatedTimestamp": 1653013543000
    },
    {
      "title": "主页",
      "frontmatter": {
        "title": "主页"
      },
      "regularPath": "/bar/",
      "relativePath": "bar/README.md",
      "key": "v-1a24d27e",
      "path": "/bar/",
      "headers": [
        {
          "level": 2,
          "title": "关于我1",
          "slug": "关于我1"
        },
        {
          "level": 3,
          "title": "内容1",
          "slug": "内容1"
        },
        {
          "level": 2,
          "title": "关于我2",
          "slug": "关于我2"
        },
        {
          "level": 3,
          "title": "内容2",
          "slug": "内容2"
        },
        {
          "level": 2,
          "title": "关于我3",
          "slug": "关于我3"
        },
        {
          "level": 3,
          "title": "内容3",
          "slug": "内容3"
        }
      ],
      "lastUpdated": "2022-05-20 10:25:43",
      "lastUpdatedTimestamp": 1653013543000
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-c1741696",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "关于我1",
          "slug": "关于我1"
        },
        {
          "level": 3,
          "title": "内容1",
          "slug": "内容1"
        },
        {
          "level": 2,
          "title": "关于我2",
          "slug": "关于我2"
        },
        {
          "level": 3,
          "title": "内容2",
          "slug": "内容2"
        },
        {
          "level": 2,
          "title": "关于我3",
          "slug": "关于我3"
        },
        {
          "level": 3,
          "title": "内容3",
          "slug": "内容3"
        }
      ],
      "lastUpdated": "2022-05-20 22:03:21",
      "lastUpdatedTimestamp": 1653055401000
    },
    {
      "title": "readbar",
      "frontmatter": {
        "title": "readbar"
      },
      "regularPath": "/bar/read.html",
      "relativePath": "bar/read.md",
      "key": "v-346476dd",
      "path": "/bar/read.html",
      "headers": [
        {
          "level": 2,
          "title": "readbar",
          "slug": "readbar"
        },
        {
          "level": 2,
          "title": "readbar1",
          "slug": "readbar1"
        },
        {
          "level": 3,
          "title": "内容1",
          "slug": "内容1"
        },
        {
          "level": 2,
          "title": "readbar2",
          "slug": "readbar2"
        },
        {
          "level": 3,
          "title": "内容2",
          "slug": "内容2"
        },
        {
          "level": 2,
          "title": "readbar3",
          "slug": "readbar3"
        },
        {
          "level": 3,
          "title": "内容3",
          "slug": "内容3"
        }
      ],
      "lastUpdated": "2022-05-20 10:25:43",
      "lastUpdatedTimestamp": 1653013543000
    },
    {
      "title": "主页",
      "frontmatter": {
        "title": "主页"
      },
      "regularPath": "/foo/",
      "relativePath": "foo/README.md",
      "key": "v-1dfa29d0",
      "path": "/foo/",
      "headers": [
        {
          "level": 2,
          "title": "关于我1",
          "slug": "关于我1"
        },
        {
          "level": 3,
          "title": "内容1",
          "slug": "内容1"
        },
        {
          "level": 2,
          "title": "关于我2",
          "slug": "关于我2"
        },
        {
          "level": 3,
          "title": "内容2",
          "slug": "内容2"
        },
        {
          "level": 2,
          "title": "关于我3",
          "slug": "关于我3"
        },
        {
          "level": 3,
          "title": "内容3",
          "slug": "内容3"
        }
      ],
      "lastUpdated": "2022-05-20 21:29:36",
      "lastUpdatedTimestamp": 1653053376000
    },
    {
      "title": "readfoo",
      "frontmatter": {
        "title": "readfoo"
      },
      "regularPath": "/foo/read.html",
      "relativePath": "foo/read.md",
      "key": "v-d488877a",
      "path": "/foo/read.html",
      "headers": [
        {
          "level": 2,
          "title": "readfoo",
          "slug": "readfoo"
        },
        {
          "level": 2,
          "title": "readfoo1",
          "slug": "readfoo1"
        },
        {
          "level": 3,
          "title": "内容1",
          "slug": "内容1"
        },
        {
          "level": 2,
          "title": "readfoo2",
          "slug": "readfoo2"
        },
        {
          "level": 3,
          "title": "内容2",
          "slug": "内容2"
        },
        {
          "level": 2,
          "title": "readfoo3",
          "slug": "readfoo3"
        },
        {
          "level": 3,
          "title": "内容3",
          "slug": "内容3"
        }
      ],
      "lastUpdated": "2022-05-20 10:25:43",
      "lastUpdatedTimestamp": 1653013543000
    },
    {
      "title": "readme",
      "frontmatter": {
        "title": "readme"
      },
      "regularPath": "/read.html",
      "relativePath": "read.md",
      "key": "v-5a5e54d5",
      "path": "/read.html",
      "lastUpdated": "2022-05-20 10:25:43",
      "lastUpdatedTimestamp": 1653013543000
    },
    {
      "title": "VuePress的使用",
      "frontmatter": {
        "title": "VuePress的使用"
      },
      "regularPath": "/guide.html",
      "relativePath": "guide.md",
      "key": "v-d795d856",
      "path": "/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "(1).创建项目，打包及运行。",
          "slug": "_1-创建项目-打包及运行。"
        },
        {
          "level": 3,
          "title": "1.进入文档，然后执行 (npm init) 产生package.json",
          "slug": "_1-进入文档-然后执行-npm-init-产生package-json"
        },
        {
          "level": 3,
          "title": "2.配置package.json，添加下述兩行.",
          "slug": "_2-配置package-json-添加下述兩行"
        },
        {
          "level": 3,
          "title": "3.进入docs文件夹 创建 README.md文件",
          "slug": "_3-进入docs文件夹-创建-readme-md文件"
        },
        {
          "level": 3,
          "title": "4.（npm run docs:dev）",
          "slug": "_4-npm-run-docs-dev"
        },
        {
          "level": 3,
          "title": "5. (sudo npm run docs:build）也就是打包，文件会多出node_modules docs文件下会多出一个.vuepress文件。",
          "slug": "_5-sudo-npm-run-docs-build-也就是打包-文件会多出node-modules-docs文件下会多出一个-vuepress文件。"
        },
        {
          "level": 3,
          "title": "参考官网 http://caibaojian.com/vuepress/guide/getting-started.html",
          "slug": "参考官网-http-caibaojian-com-vuepress-guide-getting-started-html"
        },
        {
          "level": 2,
          "title": "(2).导航栏logo。",
          "slug": "_2-导航栏logo。"
        },
        {
          "level": 3,
          "title": "1.导航栏logo, docs/.vuepress/config.js: 配置文件的入口文件配置logo，也可以是 YML 或 toml。设置logo图片。logo图片的路径：docs/.vuepress/public: 静态资源目录 public/assets/img",
          "slug": "_1-导航栏logo-docs-vuepress-config-js-配置文件的入口文件配置logo-也可以是-yml-或-toml。设置logo图片。logo图片的路径-docs-vuepress-public-静态资源目录-public-assets-img"
        },
        {
          "level": 3,
          "title": "2.右侧导航栏。",
          "slug": "_2-右侧导航栏。"
        },
        {
          "level": 3,
          "title": "3.如果对于页面不要导航条 在md页面写:navbar:false",
          "slug": "_3-如果对于页面不要导航条-在md页面写-navbar-false"
        },
        {
          "level": 3,
          "title": "4.左边侧边栏 侧边栏分组 config.js 在md页面使用 在页面中使用##",
          "slug": "_4-左边侧边栏-侧边栏分组-config-js-在md页面使用-在页面中使用"
        },
        {
          "level": 3,
          "title": "5.左边侧边栏  多个侧边栏 config.js 在md页面使用 在页面中使用##",
          "slug": "_5-左边侧边栏-多个侧边栏-config-js-在md页面使用-在页面中使用"
        },
        {
          "level": 2,
          "title": "(3).默认主题。",
          "slug": "_3-默认主题。"
        },
        {
          "level": 2,
          "title": "(4).seo 图片和设置。",
          "slug": "_4-seo-图片和设置。"
        },
        {
          "level": 2,
          "title": "(5).添加更新时间。",
          "slug": "_5-添加更新时间。"
        },
        {
          "level": 2,
          "title": "(6).官方时间插件。",
          "slug": "_6-官方时间插件。"
        }
      ],
      "lastUpdated": "2022-05-20 22:03:21",
      "lastUpdatedTimestamp": 1653055401000
    }
  ],
  "themeConfig": {
    "logo": "$withBase('/img/logo.png')",
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "VuePress",
        "link": "/guide"
      },
      {
        "text": "首页",
        "link": "/",
        "items": [
          {
            "text": "子列表1",
            "link": "/guide",
            "items": [
              {
                "text": "子列表11",
                "link": "/about"
              },
              {
                "text": "子列表12",
                "link": "/about"
              }
            ]
          },
          {
            "text": "子列表2",
            "link": "/about"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about"
      }
    ],
    "sidebar": {
      "/foo/": [
        "",
        "read"
      ],
      "/bar/": [
        "",
        "read"
      ],
      "/": [
        "",
        "guide",
        "about"
      ]
    }
  }
}